#!/usr/bin/env python

import rospy
import tf
from geometry_msgs.msg import PoseStamped

class GripTransformBroadcaster:
    def __init__(self):
        self.br = tf.TransformBroadcaster()
        rospy.Subscriber('falcon/measured_cp', PoseStamped, self.callback)

    def callback(self, msg):
        position = msg.pose.position
        orientation = msg.pose.orientation
        self.br.sendTransform(
            (position.x, position.y, position.z),
            (orientation.x, orientation.y, orientation.z, orientation.w),
            msg.header.stamp,
            "falcon_grip",
            "falcon_front"
        )

if __name__ == '__main__':
    rospy.init_node('grip_transform_broadcaster')
    GripTransformBroadcaster()
    rospy.spin()
